services:
  lb:
    image: ghcr.io/rlevidev/rinha-2026:b91b55e
    command: ["/lb", "9999", "/sockets/api1.sock", "/sockets/api2.sock"]
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "8MB"

  api1:
    image: ghcr.io/rlevidev/rinha-2026:b91b55e
    command: ["/server", "/sockets/api1.sock", "/index"]
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "171MB"

  api2:
    image: ghcr.io/rlevidev/rinha-2026:b91b55e
    command: ["/server", "/sockets/api2.sock", "/index"]
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "171MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=4m,mode=0777
