services:
  api1:
    image: ghcr.io/rlevidev/rinha-2026:6b0530b
    command: ["/server", "/sockets/api1.sock", "/index"]
    volumes:
      - sockets:/sockets
  api2:
    image: ghcr.io/rlevidev/rinha-2026:6b0530b
    command: ["/server", "/sockets/api2.sock", "/index"]
    volumes:
      - sockets:/sockets
  nginx:
    image: ghcr.io/rlevidev/rinha-2026:6b0530b
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=4m,mode=0777
